column-limit: 128
comma-style: leading
function-arrows: leading
haddock-style: multi-line
haddock-style-module: multi-line
import-export-style: diff-friendly
indent-wheres: true
indentation: 4
in-style: left-align
let-style: inline
newlines-between-decls: 2
record-brace-space: false
respectful: false
single-constraint-parens: always
unicode: detect

fixities:
  - infixr 9  .
  - infixr 5  ++, <>
  - infixl 4  <$, <*>, <*, *>, <**>
  - infixl 1  >>, >>=
  - infixr 1  =<<
  - infixr 0  $, $!
