{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}

module PageBuilder.CV (
    buildCV,
) where

import Compiler.Constants
import Compiler.HTML
import Compiler.PDF
import Compiler.Transformation.HeaderExclusion (excludeHeadersBy)
import Control.Applicative
import Data.Foldable
import Data.List (intercalate)
import Data.String (fromString)
import Data.Text (Text, drop, isPrefixOf, replace)
import Data.Text qualified as Text
import Hakyll.Core.Compiler (makeItem)
import Hakyll.Core.Item (Item(..))
import Hakyll.Core.Identifier (Identifier)
import Hakyll.Core.Identifier.Pattern (Pattern)
import Hakyll.Core.Routes (Routes)
import Hakyll.Core.Rules (Rules)
import Hakyll.Web.Template.Context (Context, constField, field, listField)
import System.FilePath.Posix ((</>))
import Text.Pandoc.Definition (Block (..), Inline (..), Pandoc)
import Text.Pandoc.Walk (walk)
import Prelude hiding (drop)
import Text.Printf (printf)


buildCV ∷ Rules ()
buildCV = do
    -- Full CV PDF
    compileFormatPDF cvContext cvPageInput pageRouteStatic [cvPdfTemplate]

    -- Concise Résumé PDF
    compileFormatPDFWith cv2Resume "résumé" resumeContext cvPageInput resumeRoute [cvPdfTemplate]

    compileFormatTransformedHTML
        transformForHTML
        cvContext
        cvPageInput
        pageRouteStatic
        [cvPageTemplate, templateDefault]


cvContext ∷ Context String
cvContext =
    contextUsing
        [ constField "AddCSS" "cv"
        , constField "NavRef" "cv"
        , constField "Title" "Curriculum Vitae"
        , flagField "HasDownloadFormats"
        , flagField "HasPDF"
        , flagField "IsCurriculumVitae"
        , sharedContext
        ]


cvPageInput ∷ Pattern
cvPageInput = fromString $ pathToPages </> "cv.md"


cvPageTemplate ∷ Identifier
cvPageTemplate = fromString $ pathToTemplates </> "cv.html"


cvPdfTemplate ∷ Identifier
cvPdfTemplate = fromString $ pathToTemplates </> "cv.latex"


cv2Resume ∷ Pandoc → Pandoc
cv2Resume =
    let theseMatchingSections ∷ [(Int, Text)]
        theseMatchingSections =
            fmap (fold . Text.words)
                <$> [ (1, "Publications & Presentations")
                    , (1, "Manuscripts in Preparation")
                    , (1, "Distinctions")
                    , (2, "Hunter College New York, NY")
                    , (2, "University of Wisconsin - Milwaukee Milwaukee, WI")
                    , (1, "Outpost Natural Foods Co-op Milwaukee, WI")
                    ]
    in  excludeHeadersBy theseMatchingSections


sharedContext ∷ Context String
sharedContext = fold
    [ cvConnectionImages
    , cvKeywords
    , cvHexEncodedBuzzwords
    ]


resumeContext ∷ Context String
resumeContext = contextUsing
    [ constField "Title" "Resume"
    , sharedContext
    ]


resumeRoute ∷ String → Routes
resumeRoute = pageRouteAlias "resume.md"


cvConnectionImages ∷ Context String
cvConnectionImages =
    fold
        [ constField "EmailImg" "email.png"
        , constField "GitHubImg" "github.png"
        , constField "LastUpdatedImg" "hourglass.png"
        , constField "PDFImg" "pdf-logo.png"
        , constField "StackOverflowImg" "stackoverflow.png"
        , constField "TimeZoneImg" "clock.png"
        , constField "WebsiteImg" "website.png"
        ]


transformForHTML ∷ Pandoc → Pandoc
transformForHTML = removeDataDirectory . niceDateSeparator


{- |
Replaces ASCII dashes with Unicode em dash in all code blocks which occur in
all headers.
-}
niceDateSeparator ∷ Pandoc → Pandoc
niceDateSeparator =
    let f (Header n a is) = Header n a $ walk h is
        f x = x
        h (Code a txt) = Code a $ replace " - " " — " txt
        h x = x
    in  walk f


{- |
Removes the prefix @data/@ from any image reference URL.
We do this because we cannot have the HTML page reference @img/doi.png@ while
also having the LaTeX documents reference @data/img/doi.png@, but both references
are required for a successfully compiled website.
This conundrum is solved by specifying @data/img/doi.png@ in the original
markdown file and pruning off the @data/@ prefix during HTML generation and
preserving the @data/@ prefix during LaTeX generation.

/It __is__ a bit ugly, but it works!/
-}
removeDataDirectory ∷ Pandoc → Pandoc
removeDataDirectory =
    let f = \case
            Image a b (url, c) | "data/" `isPrefixOf` url → Image a b (drop 5 url, c)
            x → x
    in  walk f


encodeUnicode16 :: String -> String
encodeUnicode16 = 
    let escapeChar :: Char -> String
        escapeChar = printf "%04x" . fromEnum
    in  foldMap escapeChar


cvKeywords :: Context a
cvKeywords =
    let keywordContext = field "keyword" (pure . itemBody)
    in  listField "keywords" keywordContext $ traverse makeItem keywordList


cvHexEncodedBuzzwords :: Context a
cvHexEncodedBuzzwords = 
    let blockHeader = "\nRobot Readable Relevance Regurgitation:\n"
        gluedIntoBlock = encodeUnicode16 . intercalate "\n" $ blockHeader : buzzwordList
    in  constField "BuzzwordBlock" gluedIntoBlock


keywordList :: [String]
keywordList =
    [ "Agile software development"
    , "Asymptotoic complexity"
    , "Automata theory"
    , "Benchmarking"
    , "Cryptography"
    , "Databases"
    , "Dynamic programming"
    , "Formal languages"
    , "Formal methods"
    , "Functional programming"
    , "Haskell"
    , "Integration testing"
    , "Mathematics"
    , "Optimization"
    , "Profiling"
    , "Project management"
    , "Software engineering"
    , "Technical documentation"
    , "Unit testing"
    , "Web applications"
    ]


buzzwordList :: [String]
buzzwordList = keywordList <> topSchoolList <>
    [ "101 Principles"
    , "360-degree"
    , "3D Printing"
    , "5G Network Symbiosis"
    , "5G technology"
    , "5G"
    , "A/B testing"
    , "ACL"
    , "AI-driven Music Composition"
    , "AI-driven Storytelling"
    , "AI-powered"
    , "AIX"
    , "ANR"
    , "API economy"
    , "API"
    , "API-driven"
    , "ASO"
    , "Academia"
    , "Access"
    , "Accountability"
    , "Actionable insights"
    , "Activation Key"
    , "Active Cell"
    , "Active Directory"
    , "Adaptability"
    , "Adaptive Content"
    , "Adaptive Learning Algorithms"
    , "Adaptive"
    , "Add-on"
    , "Advanced Materials Discovery"
    , "Advertising ID"
    , "Advertising"
    , "Affiliate Marketing"
    , "Affinity Marketing"
    , "Agile DevOps Culture"
    , "Agile leadership"
    , "Agile methodology"
    , "Agile"
    , "Alert Box"
    , "Algorithm"
    , "Ambient Computing"
    , "Ambient Energy Harvesting"
    , "Ambient Intelligence Ecosystems"
    , "Ambient Intelligence Integration"
    , "Ambient Intelligence"
    , "Ambient computing"
    , "Ambient intelligence"
    , "Ambient marketing"
    , "Analytics"
    , "Android"
    , "Anti-Aliasing"
    , "Antivirus"
    , "App"
    , "Application Programming Interface"
    , "Application"
    , "Archive"
    , "Array"
    , "Artificial Intelligence Driven Supply Chain Management"
    , "Artificial Intelligence"
    , "Artificial intelligence"
    , "As-a-Service"
    , "Assembler"
    , "Assembly Language"
    , "Attention to detail"
    , "Augmented Biology"
    , "Augmented Democracy Platforms"
    , "Augmented Reality Commerce"
    , "Augmented Reality Ecosystem"
    , "Augmented reality"
    , "Augmented"
    , "Autocorrect"
    , "Autofill"
    , "Automated"
    , "Autonomous Agriculture Drones"
    , "Autonomous Decision Engines"
    , "Autonomous Vehicles Integration"
    , "Autonomous"
    , "Autoscaling"
    , "BASIC"
    , "BIOS"
    , "BSOD"
    , "Backdoor"
    , "Backend"
    , "Backup"
    , "Bare Metal Restore"
    , "Bash"
    , "Batch Process"
    , "Behavioral Targeting"
    , "Behavioral analytics"
    , "Behavioral economics"
    , "Benchmark"
    , "Best Practices"
    , "Big Data"
    , "Big Sur"
    , "Big data"
    , "Big data"
    , "Bio-Resilience"
    , "Bio-Responsive Architecture"
    , "Bio-Responsive Environments"
    , "Bio-inspired"
    , "Bioacoustic Sensing"
    , "Biohacking Optimization"
    , "Biohacking Synergy"
    , "Biohacking"
    , "Biohazard Defense Systems"
    , "Bioinformatics Fusion"
    , "Bioinformatics Revolution"
    , "Bioinformatics"
    , "Biometric Authentication Mesh"
    , "Biometric authentication"
    , "Biometric wearables"
    , "Bitcoin"
    , "Black Box Testing"
    , "Bleeding edge"
    , "Bleeding-edge technology"
    , "Bloatware"
    , "Block-Based Coding"
    , "Blockchain Biohacking"
    , "Blockchain Integration"
    , "Blockchain Oracles"
    , "Blockchain as a Service (BaaS)"
    , "Blockchain as a service (BaaS)"
    , "Blockchain"
    , "Blockchain-Powered Supply Chain"
    , "Blockchain-enabled"
    , "Blue ocean strategy"
    , "Blue sky thinking"
    , "Bootstrap"
    , "Bounce Rate"
    , "Brain-Computer Interface Gaming"
    , "Brand Identity"
    , "Brand advocacy"
    , "Brand equity"
    , "Brand loyalty"
    , "Brand positioning"
    , "Brand"
    , "Break Even Point"
    , "Breakthrough innovation"
    , "Breakthrough"
    , "Bring your own Device"
    , "Brownfield"
    , "Browser Engine"
    , "Browser Extension"
    , "Bug"
    , "Build"
    , "Buisness-To-Buisness"
    , "Buisness-To-Customer"
    , "Business Accelerator"
    , "Business Angel"
    , "Business Intelligence Tools"
    , "Buzzword compliant"
    , "Buzzword"
    , "Buzzworthy"
    , "Bytecode"
    , "C"
    , "C#"
    , "C++"
    , "CGI"
    , "CamelCase"
    , "Carbon Neutral"
    , "Case Study"
    , "Catalina"
    , "Cell Reference"
    , "Cell"
    , "Character Encoding"
    , "ChatGPT"
    , "ChatOps"
    , "Chatbot"
    , "Chatbots"
    , "Checksum"
    , "Chief Executive Officer"
    , "Chief Financial Officer"
    , "Chief Operating Officer"
    , "Chief Technology Officer"
    , "Circular economy"
    , "Citizen data scientist"
    , "Class"
    , "Clean Code"
    , "Clean Install"
    , "Clicks"
    , "Clip Art"
    , "Clipboard"
    , "Close the Loop"
    , "Cloud Compution"
    , "Cloud Working"
    , "Cloud"
    , "Cloud-Native Transformation"
    , "Cloud-Native"
    , "Cloud-native"
    , "Codec"
    , "Cognitive Augmentation Networks"
    , "Cognitive Computing Solutions"
    , "Cognitive Load"
    , "Cognitive computing"
    , "Cognitive load"
    , "Cognitive"
    , "Collaborate"
    , "Collaboration"
    , "Command Line Interface"
    , "Command Prompt"
    , "Commercial Software"
    , "Compile"
    , "Compiler"
    , "Compression"
    , "Computer Vision"
    , "Computer science"
    , "Conscious Computing Frameworks"
    , "Consumer-zentriert"
    , "Container"
    , "Container"
    , "Content Management System"
    , "Content Shock"
    , "Contextual Marketing"
    , "Contextual Menu"
    , "Continuous Integration/Continuous Deployment (CI/CD) Orchestration"
    , "Continuous integration"
    , "Control Panel"
    , "Convergent"
    , "Conversational AI Interfaces"
    , "Conversational commerce"
    , "Conversion Rate Optimisation"
    , "Copy"
    , "Core competency"
    , "Corporate agility"
    , "Corporate social responsibility (CSR)"
    , "Corporate wellness"
    , "Cost-Per-Click"
    , "Coworking"
    , "Coworking-Space"
    , "Crash"
    , "Creative"
    , "Creativity"
    , "Critical thinking"
    , "Cron"
    , "Cross-Paltfworm"
    , "Cross-functional"
    , "Cross-platform software"
    , "Cross-platform"
    , "Crowdfunding"
    , "Crowdsourced innovation"
    , "Crowdsourced"
    , "Crowdsourcing"
    , "Crypto-Ecology"
    , "Crypto-Ethics Frameworks"
    , "Crypto-Resilience"
    , "Cryptocurrency Wallet Security"
    , "Cryptocurrency"
    , "Cryptoeconomic Incentives"
    , "Cryptographic agility"
    , "Cultural intelligence"
    , "Cursor"
    , "Customer Experience"
    , "Customer Journey"
    , "Customer Lifetime Value"
    , "Customer acquisition"
    , "Customer churn"
    , "Customer empowerment"
    , "Customer experience"
    , "Customer journey"
    , "Customer persona"
    , "Customer retention"
    , "Customer satisfaction"
    , "Customer-Centric"
    , "Customer-Relationship-Management"
    , "Customer-To-Customer"
    , "Customer-centric"
    , "Cut"
    , "Cutting-edge solution"
    , "Cutting-edge"
    , "Cyber resilience"
    , "Cyber-Physical Resilience"
    , "Cyber-Physical Systems Fusion"
    , "Cyber-physical Systems"
    , "Cyber-physical"
    , "Cyber-secure"
    , "Cybersecurity"
    , "DBMS"
    , "DCIM"
    , "DLC"
    , "DOS"
    , "Daemon"
    , "Dark Data Utilization"
    , "Dark Matter Analytics"
    , "Dark Mode"
    , "Dark Web Analytics"
    , "Dark analytics"
    , "Dark data"
    , "Dark social"
    , "Dark web analytics"
    , "Dark web monitoring"
    , "Dark web"
    , "Dashboard"
    , "Data Anonymization"
    , "Data Encryption"
    , "Data Ethics"
    , "Data Governance"
    , "Data Management"
    , "Data Mining"
    , "Data Science"
    , "Data Type"
    , "Data Warehousing"
    , "Data engineering"
    , "Data governance"
    , "Data integration"
    , "Data lakes"
    , "Data monetization"
    , "Data science"
    , "Data-Driven Marketing"
    , "Data-driven Innovation"
    , "Data-driven"
    , "Database"
    , "Datafication"
    , "Deadlock"
    , "Debug"
    , "Debugger"
    , "Decentralized Autonomous Organizations (DAOs)"
    , "Decentralized Autonomous Organizations"
    , "Decentralized Autonomous Vehicles"
    , "Decentralized Finance (DeFi)"
    , "Decentralized Finance"
    , "Decentralized Identity Management"
    , "Decentralized Identity"
    , "Decentralized finance"
    , "Declarative programming"
    , "Deep Dive Technology"
    , "Deep Learning"
    , "Deep Web"
    , "Deep dive"
    , "Deep learning"
    , "Deepfake Detection Systems"
    , "Default Program"
    , "Dependability"
    , "Deployment"
    , "Deprecated"
    , "Design Pattern"
    , "Design Thinking"
    , "Design sprint"
    , "Design thinking"
    , "Desktop Publishing"
    , "Desktop Software"
    , "Desktop"
    , "DevOps"
    , "DevOps"
    , "Dialog Box"
    , "Digital Asset Tokenization"
    , "Digital Asset"
    , "Digital Biomimicry"
    , "Digital Knowledge Management"
    , "Digital Native"
    , "Digital Rights Management"
    , "Digital Signature"
    , "Digital Storytelling"
    , "Digital Twin Revolution"
    , "Digital Unplugged"
    , "Digital disruption"
    , "Digital transformation"
    , "Digital trust"
    , "Digital twin"
    , "Direct-to-Consumer"
    , "Direct3D"
    , "DirectX"
    , "Directory"
    , "Disintermediate"
    , "Disk Image"
    , "Disrupt"
    , "Disruptive innovation"
    , "Disruptive technology"
    , "Disruptive"
    , "Disruptor"
    , "Distributed Hash Tables"
    , "Distributed Ledger Technology (DLT)"
    , "Distributed systems"
    , "Dock"
    , "Document"
    , "Donationware"
    , "Downsizing"
    , "Drag and Drop"
    , "Driver"
    , "Drone Swarm Light Shows"
    , "Drop Down Menu"
    , "Dropshipping"
    , "Dual Boot"
    , "Dynamic DNA Computing"
    , "Dynamic Spectrum Allocation"
    , "Dynamic"
    , "EPS"
    , "ERP"
    , "Early Adopter"
    , "Ecosystem"
    , "Ecosystem-driven"
    , "Edge AI"
    , "Edge Computing Synergy"
    , "Edge Computing"
    , "Edge Intelligence Platforms"
    , "Edge analytics"
    , "Edge computing"
    , "Edge-to-Cloud Continuum"
    , "Edge-to-Edge Computing"
    , "Edtech"
    , "Effective communication"
    , "El Capitan"
    , "Elastic computing"
    , "Elasticity"
    , "Electron"
    , "Emerging Markets"
    , "Emoji"
    , "Emotional Analytics"
    , "Emotional Intelligence Algorithms"
    , "Emotional Robotics"
    , "Emotional analytics"
    , "Emotional branding"
    , "Emotional intelligence"
    , "Empathic Computing Solutions"
    , "Employee Advocacy Marketing"
    , "Employee experience"
    , "Empower"
    , "Enabler"
    , "Encoding"
    , "Encryption"
    , "End-To-End"
    , "Energy Harvesting Technologies"
    , "Enterprise Resource Planning"
    , "Enterprise-Resource-Planning"
    , "Establishment"
    , "Ethical AI Governance"
    , "Ethical AI"
    , "Ethical Tech Governance"
    , "Ethical hacking"
    , "Excel"
    , "Exception"
    , "Executable File"
    , "Exit Strategy"
    , "Exo-Bioengineering"
    , "Exo-Suit Augmentation"
    , "Exoplanetary Data Mining"
    , "Exoplanetary Exploration"
    , "Exoplanetary Mining"
    , "Experience economy"
    , "Experience-driven"
    , "Experiential Learning Platforms"
    , "Explainable AI Frameworks"
    , "Explainable AI"
    , "Exponential Technologies Convergence"
    , "Exponential growth"
    , "Exponential"
    , "Export"
    , "Extended Reality"
    , "Extensible"
    , "FPS"
    , "Facility Management"
    , "Factory Reset"
    , "Fashion"
    , "Fast Fashion"
    , "Favorites"
    , "Federated Learning Networks"
    , "Fiber To The Desk"
    , "File Association"
    , "File Compression"
    , "File Extension"
    , "File Format"
    , "File Type"
    , "File"
    , "Filename"
    , "Filter Bubble"
    , "Finder"
    , "Fintech Quantum Leap"
    , "Fintech"
    , "Firmware"
    , "Flag"
    , "Flat File"
    , "Flexibility"
    , "Floor Management"
    , "Flywheel"
    , "Focus"
    , "Folder"
    , "Fork"
    , "Form"
    , "Framework"
    , "Freemium"
    , "Freeware"
    , "Frictionless experience"
    , "Frontend"
    , "Frozen"
    , "Function"
    , "Future-proof"
    , "Future-proofing"
    , "Futuristic"
    , "Fuzzy Logic"
    , "GNU"
    , "GUI"
    , "GUID"
    , "Game-changer"
    , "Game-changing"
    , "Gamification"
    , "Gamified Learning Experiences"
    , "Gamified Learning"
    , "Gamified Marketing"
    , "Gamified"
    , "Gamma Correction"
    , "Garbage Collection"
    , "Gen Z"
    , "Gender Equality"
    , "Gene Editing Therapies"
    , "Generation Y"
    , "Genomic Data Sovereignty"
    , "Geofencing"
    , "Geotargeting"
    , "Geotargiting"
    , "Global Depression"
    , "Global"
    , "Globale Depression"
    , "Globalized"
    , "Gnutella"
    , "Golden Master"
    , "Green IT"
    , "Green Tech Innovations"
    , "Green Tech"
    , "Green energy"
    , "Green"
    , "Greenfield"
    , "Greenwashing"
    , "Grep"
    , "Growth Hacking"
    , "Growth hacking"
    , "Growth mindset"
    , "Hackathon"
    , "Haptic Feedback Systems"
    , "Hash"
    , "Hashtag"
    , "Headless"
    , "Heuristic"
    , "High Sierra"
    , "High-Level Language"
    , "Hipster"
    , "Holacracy"
    , "Holistic approach"
    , "Holistic"
    , "Holistisches Marketing"
    , "Holochain Orchestration"
    , "Holochain Platforms"
    , "Holochron Technology"
    , "Holographic Interfaces"
    , "Holographic Telepresence Systems"
    , "Home Office"
    , "Horizontal Market Software"
    , "Host"
    , "Hotfix"
    , "Human-Centric Design Thinking"
    , "Human-Machine Symbiosis"
    , "Human-centric"
    , "Humanized Automation"
    , "Hyperautomation"
    , "Hyperconnected Collaboration"
    , "Hyperconvergence"
    , "Hyperledger"
    , "Hyperlocal"
    , "Hyperpersonalization"
    , "Hypervisor"
    , "IPC"
    , "ISR"
    , "Icon"
    , "Ideate"
    , "Ideation session"
    , "Ideation"
    , "Illegal Operation"
    , "Image Scaling"
    , "Immersive Cybersecurity"
    , "Immersive Storytelling"
    , "Immersive Virtual Experiences"
    , "Immersive experience"
    , "Immersive storytelling"
    , "Impactful"
    , "Impertative programming"
    , "Import"
    , "In the loop"
    , "In-App Purchase"
    , "Inclusive design"
    , "Inclusivity"
    , "Index"
    , "Industry 4.0"
    , "Industry leading"
    , "Influencer Marketing"
    , "Influencer marketing"
    , "Information Society"
    , "Initial Public Offering"
    , "Innovate"
    , "Innovation ecosystem"
    , "Innovation hub"
    , "Innovation lab"
    , "Innovation pipeline"
    , "Innovation"
    , "Innovative"
    , "Innovators"
    , "Insertion Point"
    , "Install"
    , "Installer"
    , "Integrated"
    , "Intelligent automation"
    , "Interactive Video"
    , "Internet Of Things"
    , "Internet Pure Player"
    , "Internet of Things (IoT)"
    , "Internet of things (IoT)"
    , "Interoperability"
    , "Interpersonal skills"
    , "Interpreter"
    , "Intuitive User Empowerment"
    , "Invested in"
    , "Iteration"
    , "Iterative"
    , "JDBC"
    , "JRE"
    , "JVM"
    , "Java"
    , "Jour Fixe"
    , "KDE"
    , "KOffice"
    , "Kernel"
    , "Key Performance Indicator"
    , "Key Performance Indicators"
    , "Keyboard Shortcut"
    , "Keylogger"
    , "Keynote"
    , "Kick-Off Meeting"
    , "Knowledge sharing"
    , "Knowledge transfer"
    , "LFN"
    , "Launcher"
    , "Leadership"
    , "Lean startup"
    , "Learnings"
    , "Legal Tech"
    , "Leopard"
    , "Leverage Effect"
    , "Leverage"
    , "Library"
    , "Lifehack"
    , "Linux"
    , "Lion"
    , "Liquid Workforce Management"
    , "Liquid data"
    , "Liquid leadership"
    , "Liquid workforce"
    , "Literature review"
    , "Log File"
    , "Logic Error"
    , "Logic programming"
    , "Loop"
    , "Lose-Lose"
    , "Lossless"
    , "Lossy"
    , "Low Hanging Fruits"
    , "Low-Level Language"
    , "Loyalty As Service"
    , "Lua"
    , "MAMP"
    , "MBR"
    , "MVC"
    , "Machine Language"
    , "Machine Learning Operations (MLOps)"
    , "Machine Vision"
    , "Machine learning"
    , "Machine-to-machine"
    , "Macro"
    , "Make it pop"
    , "Malware"
    , "Market Segmentation"
    , "Marketing Automation"
    , "Marketing Efforts"
    , "Masterclass"
    , "Mavericks"
    , "Maximize"
    , "Media Compression"
    , "Memory Leak"
    , "Mentoring"
    , "Menu Bar"
    , "Meta-learning"
    , "Metafile"
    , "Metaverse Economy Boost"
    , "Metaverse Real Estate"
    , "Metaverse Realities"
    , "Metaverse"
    , "Method"
    , "Micro Moments"
    , "Micro-influencer marketing"
    , "Microkernel"
    , "Microservice Driven Personalization Engine"
    , "Microservices"
    , "Microsoft"
    , "Middleware"
    , "Millennials"
    , "Mindfulness Tech Integration"
    , "Mindfulness at work"
    , "Mindset"
    , "Mindshare"
    , "Minification"
    , "Minimize"
    , "Minimum Viable Product"
    , "Minimum viable product (MVP)"
    , "Mobile Optimization"
    , "Mobile first"
    , "Mobile-first"
    , "Modular"
    , "Mojave"
    , "Monetization strategy"
    , "Monetize"
    , "Monterey"
    , "Motion Tween"
    , "Mount"
    , "Mountain Lion"
    , "Moving forward"
    , "Multichannel Marketing"
    , "Multichannel marketing"
    , "Multichannel"
    , "Multiexperience"
    , "Multitasking"
    , "Multithreading"
    , "Music Tracker"
    , "MySQL"
    , "NFT"
    , "NOS"
    , "Nano"
    , "Nano-Medicine Innovations"
    , "Nano-scale Robotics"
    , "Nanobot Swarms"
    , "National security"
    , "Native File"
    , "Need Generation"
    , "Net Neutrality"
    , "Net zero"
    , "NetBIOS"
    , "Network effect"
    , "Networked"
    , "Networking"
    , "Networking"
    , "Neural Interface Protocols"
    , "Neural Network Empowerment"
    , "Neural Networks"
    , "Neural networks"
    , "Neuro-Adaptive Systems"
    , "Neuro-Digital Integration"
    , "Neuro-Diversity Inclusion"
    , "Neuro-Enhanced Reality"
    , "Neuro-Inclusive Design"
    , "Neuro-Security Protocols"
    , "Neuro-Tech Integration"
    , "Neuroaesthetics Integration"
    , "Neurocapitalism"
    , "Neurofeedback Optimization"
    , "Neurofeedback Platforms"
    , "Neurofeedback"
    , "Neuromorphic Computing Integration"
    , "Neuromorphic Integration"
    , "Neuromorphic Security Systems"
    , "New Work"
    , "Next Generation"
    , "Next-gen"
    , "Niche market"
    , "Niche"
    , "No-Brainer"
    , "OCR"
    , "ODBC"
    , "OLE"
    , "OOP"
    , "OS X"
    , "Object"
    , "Object-oriented programming"
    , "Objective-C"
    , "Office"
    , "Omni-channel"
    , "Omnichannel experience"
    , "Omnichannel"
    , "On-demand"
    , "Opacity"
    , "Open Firmware"
    , "Open Source Quantum Computing"
    , "Open Source"
    , "Open Source"
    , "Open Stack"
    , "Open-source"
    , "OpenGL"
    , "Operating System"
    , "Operating systems"
    , "Opportunities"
    , "Optimize"
    , "Organic growth"
    , "Organization"
    , "Out-of-the-box"
    , "Outsourcing"
    , "PCAP"
    , "PUM"
    , "PUP"
    , "Paid Placement"
    , "Pain Points"
    , "Paradigm Shift"
    , "Paradigm shift"
    , "Paradigm-shifting"
    , "Parameter"
    , "PascalCase"
    , "Password Manager"
    , "Paste"
    , "Patch"
    , "Path"
    , "Patience"
    , "Pay-Per-Click"
    , "Peer-To-Peer"
    , "Pennystocks"
    , "Performance Marketing"
    , "Performance tuning"
    , "Perl"
    , "Permissions"
    , "Personal data sovereignty"
    , "Personalization"
    , "Personalized Genomic Medicine"
    , "Personalized"
    , "Pervasive"
    , "Pioneer"
    , "Piracy"
    , "Pitch Desk"
    , "Pitch"
    , "Pivot point"
    , "Pivot"
    , "Plain Text"
    , "Platform-agnostic"
    , "Plug-in"
    , "Podcast"
    , "Pop-Up"
    , "Portable Software"
    , "Post Quantum Cryptography"
    , "PowerPoint"
    , "PowerShell"
    , "Prebinding"
    , "Precision Agriculture Technologies"
    , "Precision Agriculture"
    , "Precision Analytics"
    , "Precision Health Platforms"
    , "Precision Medicine Analytics"
    , "Predictive Personalization"
    , "Predictive analytics"
    , "Predictive maintenance"
    , "Predictive policing"
    , "Predictive"
    , "Proactive"
    , "Problem solving"
    , "Process"
    , "Processing"
    , "Program"
    , "Programming Language"
    , "Programming"
    , "Project-Based Learning"
    , "Proprietary Software"
    , "Proximity Marketing"
    , "Pseudocode"
    , "Public Domain"
    , "Python"
    , "QBE"
    , "QoS"
    , "Quantifiable results"
    , "Quantum AI as a Service"
    , "Quantum Acceleration"
    , "Quantum Algorithms"
    , "Quantum Augmented Reality"
    , "Quantum Biomimicry"
    , "Quantum Cognitive Computing"
    , "Quantum Computing Resilience"
    , "Quantum Computing Synergy"
    , "Quantum Computing"
    , "Quantum Consciousness Exploration"
    , "Quantum Cryptocurrency Mining"
    , "Quantum Cryptography"
    , "Quantum Cryptokitties"
    , "Quantum Data Integrity"
    , "Quantum Economic Models"
    , "Quantum Emotional Intelligence"
    , "Quantum Empathy Networks"
    , "Quantum Encryption Mesh"
    , "Quantum Encryption"
    , "Quantum Energy Harvesting"
    , "Quantum Ethics Framework"
    , "Quantum Experiences"
    , "Quantum Gaming Platforms"
    , "Quantum Hedge Funds"
    , "Quantum Internet Infrastructure"
    , "Quantum Internet"
    , "Quantum Machine Learning"
    , "Quantum Mesh Computing"
    , "Quantum Mesh Internet"
    , "Quantum Mesh Networks"
    , "Quantum Meshing"
    , "Quantum Neural Networks"
    , "Quantum Precision Medicine"
    , "Quantum Resilience"
    , "Quantum Robotic Surgery"
    , "Quantum Sensing Networks"
    , "Quantum Supply Chain Visibility"
    , "Quantum Swarm Learning"
    , "Quantum Weather Prediction"
    , "Quantum cloud computing"
    , "Quantum communication"
    , "Quantum computing"
    , "Quantum cryptography"
    , "Quantum economy"
    , "Quantum encryption"
    , "Quantum internet"
    , "Quantum key distribution"
    , "Quantum leap"
    , "Quantum machine learning"
    , "Quantum sensing"
    , "Quantum supremacy"
    , "Quantum-Assisted Design"
    , "Quantum-Enhanced Sensing"
    , "Quantum-Inspired Design"
    , "Quantum-Resistant Encryption"
    , "Quantum-Safe Cryptography"
    , "Quantum-Safe Encryption"
    , "Quantum-enhanced Financial Trading"
    , "Quantum-enhanced Imaging"
    , "Quantum-enhanced Materials"
    , "Quantum-ready"
    , "Quantum-resistant"
    , "Quantum-safe cryptography"
    , "Query"
    , "QuickTime"
    , "RDBMS"
    , "RPC"
    , "RTE"
    , "Race Condition"
    , "Rapid prototyping"
    , "Raw Data"
    , "Readme"
    , "Real Time Marketing"
    , "Real World Problems"
    , "Real-time Predictive Maintenance"
    , "Real-time analytics"
    , "Real-time"
    , "Real-world evidence"
    , "Rebranding"
    , "Recycle Bin"
    , "Red teaming"
    , "Redefine"
    , "Regenerative"
    , "Register"
    , "Registry"
    , "Reimage"
    , "Relational Database"
    , "Relationship Marketing"
    , "Reliability"
    , "Remote Desktop"
    , "Remote Workforce"
    , "Remote collaboration"
    , "Remote onboarding"
    , "Renewable Energy"
    , "Repository"
    , "Reserach"
    , "Resilience Engineering"
    , "Resilient Infrastructure Orchestration"
    , "Resilient Quantum Networks"
    , "Resilient"
    , "Reskilling Platforms"
    , "Resourcefulness"
    , "Responsive Web Design"
    , "Responsive"
    , "Retargeting"
    , "Return on Investment"
    , "Revenue stream"
    , "Ribbon"
    , "Rich Text"
    , "Ripping"
    , "Roadmap"
    , "Robo-Advisory Platforms"
    , "Robo-advisors"
    , "Robotic Process Orchestration"
    , "Robotic Swarm Autonomy"
    , "Robotic Swarm Orchestration"
    , "Robotic process automation (RPA)"
    , "Robotic"
    , "Robotics"
    , "Robust"
    , "Root"
    , "Rootkit"
    , "Rosetta"
    , "Ruby"
    , "Runtime Error"
    , "Runtime"
    , "SDK"
    , "SDLC"
    , "SDS"
    , "SMB"
    , "SNMP"
    , "SQL Injection"
    , "SQL"
    , "SRE"
    , "SaaS (Software as a Service)"
    , "SaaS"
    , "Samba"
    , "Sandboxing"
    , "Scalability"
    , "Scalable solution"
    , "Scalable"
    , "Scareware"
    , "Schema"
    , "Screen Saver"
    , "Screenshot"
    , "Script"
    , "Scroll Bar"
    , "Scrolling"
    , "Seamless"
    , "Search engine optimization"
    , "Second-Screen"
    , "Secure Boot"
    , "Self Driving"
    , "Self-Healing Cybersecurity"
    , "Self-Optimizing Algorithms"
    , "Self-Optimizing Systems"
    , "Self-healing"
    , "Self-optimizing"
    , "Semaphore"
    , "Sementic Web"
    , "Sensorization"
    , "Sentiment analysis"
    , "Serverless"
    , "Service Mesh"
    , "Service Pack"
    , "SharePoint"
    , "Shareholder"
    , "Shareware"
    , "Shell"
    , "Sideload"
    , "Sierra"
    , "Silent Install"
    , "Siloed"
    , "Skin"
    , "Smart Buisness Automation"
    , "Smart Cities"
    , "Smart Dust Technology"
    , "Smart cities"
    , "Smart contracts"
    , "Smart"
    , "Snackable Content"
    , "Snake Case"
    , "Snapchat"
    , "Snapshot"
    , "Snippet"
    , "Snow Leopard"
    , "Social Augmentation Platforms"
    , "Social Engineering"
    , "Social Entrepreneurship"
    , "Social Media Marketing"
    , "Social engineering"
    , "Social listening"
    , "Social media engagement"
    , "Social proof"
    , "Socially responsible"
    , "Soft Token"
    , "Software development life cycle"
    , "Software"
    , "Software-Defined Networking"
    , "Sonoma"
    , "Soulution"
    , "Source Code"
    , "Space Debris Cleanup"
    , "Space Tourism Infrastructure"
    , "Spatial Audio Experiences"
    , "Spatial Computing Interfaces"
    , "Spatial Computing Synergy"
    , "Spatial computing"
    , "Spellcheck"
    , "Spin-Up"
    , "Spirit"
    , "Spool"
    , "Spreadsheet"
    , "Spreadsheets"
    , "Sprite"
    , "Spyware"
    , "Stakeholder"
    , "Start Menu"
    , "Startup"
    , "Status Bar"
    , "Stealth mode"
    , "Storyscaping"
    , "Strategic partnership"
    , "Streamline"
    , "Struct"
    , "Subdirectory"
    , "Supply Chain Resilience"
    , "Supply chain resilience"
    , "Supply chain visibility"
    , "Survival strategy"
    , "Sustainability"
    , "Sustainable Disruption"
    , "Sustainable Energy Grid Orchestration"
    , "Sustainable Tech Ecosystems"
    , "Sustainable Urban Tech"
    , "Sustainable development"
    , "Sustainable"
    , "Swarm Intelligence Optimization"
    , "Swarm Intelligence Orchestration"
    , "Swarm Robotics Choreography"
    , "Swarm Robotics Collaboration"
    , "Swarm Robotics"
    , "Swarm intelligence"
    , "Swarm robotics"
    , "Swift"
    , "Swipe File"
    , "Symbolic Link"
    , "Synergistic Alliances"
    , "Synergistic Paradigms"
    , "Synergistic"
    , "Synergize"
    , "Synergy"
    , "Syntax Error"
    , "Synthetic Biology Platforms"
    , "Synthetic Consciousness"
    , "Synthetic Sentience"
    , "Synthetic biology"
    , "System Call"
    , "System Preferences"
    , "System Software"
    , "System testing"
    , "Systray"
    , "TED Talk"
    , "TWAIN"
    , "Tab"
    , "Tagging"
    , "Take Offline"
    , "Taskbar"
    , "Teamwork"
    , "Technical Debt"
    , "Template"
    , "Terminal"
    , "Text Box"
    , "Text Editor"
    , "Theoretical computer science"
    , "Thought Leader"
    , "Thought leadership"
    , "Threat hunting"
    , "Threat intelligence"
    , "Thumbnail"
    , "Tiger"
    , "Time management"
    , "Timestamp"
    , "Title Bar"
    , "Toolbar"
    , "Toolchain"
    , "Toolchain"
    , "Tooltip"
    , "Touchpoint"
    , "Transformational"
    , "Transparency"
    , "Trash"
    , "Trojan Horse"
    , "Trunk based Development"
    , "Trustless"
    , "Tutorial"
    , "Typecasting"
    , "UML"
    , "UUID"
    , "UWP"
    , "Undo"
    , "Unicorns"
    , "Universal Basic Income Platforms"
    , "Unix"
    , "Unmount"
    , "User experience (UX)"
    , "User-centric design"
    , "User-generated content"
    , "Utility"
    , "Value proposition"
    , "Value stream mapping"
    , "Value-added"
    , "Vegan"
    , "Ventura"
    , "Venture-Capital"
    , "Version Control"
    , "Vertical Market Software"
    , "Viral"
    , "Virality"
    , "Virtual Desktop Infrastructure"
    , "Virtual Event"
    , "Virtual Machine"
    , "Virtual Reality Therapeutics"
    , "Virtual Reality Therapy"
    , "Virtual Reality"
    , "Virtual collaboration"
    , "Virtual reality"
    , "Virtual"
    , "Virtualization"
    , "Virus Definition"
    , "Virus"
    , "Visionary"
    , "Visual Basic"
    , "Visual Statements"
    , "Visual Storytelling"
    , "Voice recognition"
    , "Voice search"
    , "Vulkan"
    , "WAMP"
    , "WDDM"
    , "WIMP"
    , "WYSIWYG"
    , "Wallpaper"
    , "Wallstreet"
    , "Waveform"
    , "Wearable Health Tech"
    , "Wearable"
    , "Wearables"
    , "Web 2.0"
    , "Web Browser"
    , "Web Personalization"
    , "Web3.0"
    , "Webinar"
    , "White Box Testing"
    , "White Label"
    , "Widget"
    , "Win-win"
    , "Win32"
    , "Window"
    , "Windows 10"
    , "Windows 11"
    , "Windows 7"
    , "Windows 8"
    , "Windows RT"
    , "Windows Vista"
    , "Windows XP"
    , "Windows"
    , "Winsock"
    , "Wizard"
    , "Word Processor"
    , "Word Wrap"
    , "Word"
    , "WordArt"
    , "Work ethic"
    , "Workflow"
    , "Worm"
    , "Wrapper"
    , "XAML"
    , "Yosemite"
    , "Youtube Algorithm"
    , "Zero Day Exploit"
    , "Zero Trust Security"
    , "Zero emissions"
    , "Zero trust"
    , "Zero-Day Vulnerability"
    , "Zero-Emissions"
    , "Zero-Touch Deployment"
    , "Zero-Trust Security Architecture"
    , "Zero-Waste"
    , "Zero-day"
    , "Zero-touch"
    , "Zip Bomb"
    , "bleeding-edge"
    , "eCommerce"
    , "iOS"
    , "iTunes"
    , "macOS"
    ]

topSchoolList :: [String]
topSchoolList =
    [ "Carnegie Mellon University"
    , "Massachusetts Institute of Technology"
    , "Stanford University"
    , "University of California - Berkeley"
    , "University of Illinois - Urbana-Champaign"
    , "Cornell University"
    , "Georgia Institute of Technology"
    , "University of Texas - Austin"
    , "University of Washington"
    , "Princeton University"
    , "University of Michigan - Ann Arbor"
    , "Columbia University"
    , "California Institute of Technology"
    , "University of California - Los Angeles"
    , "University of California - San Diego"
    , "University of Wisconsin - Madison"
    , "Harvard University"
    , "University of Maryland - College Park"
    , "Purdue University - West Lafayette"
    , "University of Pennsylvania"
    , "Duke University"
    , "University of Southern California"
    , "Yale University"
    , "Johns Hopkins University"
    , "University of Chicago"
    , "University of Massachusetts - Amherst"
    , "Brown University"
    , "New York University"
    , "Northeastern University"
    , "Northwestern University"
    , "Ohio State University"
    , "Rice University"
    , "University of California - Irvine"
    , "University of California - Santa Barbara"
    , "University of North Carolina - Chapel Hill"
    ]
